# tasks file
---
- include: repository.yml
  when:
    - r_cran_repo == true
  tags:
    - configuration
    - r
    - r-repository

- include: install.yml
  tags:
    - configuration
    - r
    - r-install

- include: packages.yml
  tags:
    - configuration
    - r
    - r-packages
